    - title: "`functional`: Functions and functionals"
      desc: Functional interfaces for differentiable programming.
      package: {__PKGNAME__}.functional
      options:
        dynamic: true
        children: separate
      contents:
        - name: activation
        - name: cmass
        - name: connectopy
        - name: cov
        # - kind: page
        #   summary: "`cov`: Covariances and correlations"
        #   path: functional.cov
        #   package: {__PKGNAME__}.functional.cov
        #   contents:
        #     - name: cov
        #     - name: corr
        #     - name: partialcorr
        # - name: fourier
        # - name: graph
        # - name: interpolate
        # - name: kernel
        # - name: matrix
        # - name: semidefinite
        # - name: sparse
        # - name: sphere
        # - name: sylo
        # - name: symmap
        # - name: tsconv
        # - name: utils
        # - name: window

    # - title: "`loss`: Loss and regularisation"
    #   desc: Functional and module interfaces for common loss functions.
    #   package: {__PKGNAME__}.loss
    #   options:
    #     dynamic: true
    #     children: separate
    #   contents:
    #     - name: functional
    #     - name: nn
    #     - name: scalarise
    #     - name: scheme

static-resources:
  - icon-hypercoil.png
  - logo-hypercoil.svg
