name: CI
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10.4'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ‘2’
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade "jax[cpu]"
        python -m pip install .
        python -m pip install pytest
        python -m pip install vtk
        python -m pip install https://github.com/wiheto/netplotbrain/archive/535a07bb7d2be1a2c95746bcb82b41e69f19a8f1.tar.gz
        python -m pip install https://github.com/rciric/surfplot/archive/9b4a1e65aac89daf5e6747cee0419b6fc39d2392.tar.gz
        python -m pip install --upgrade --force-reinstall --no-deps https://github.com/deepmind/distrax/archive/4787902ae49ccfccb1c903e759d15bc61e6a20b4.tar.gz
        python -m pip install --upgrade --force-reinstall --no-deps scipy==1.9.0
        python -m pip install scikit-image
        python -m pip install pingouin
        python -m pip install nilearn
        python -m pip install setuptools
        python -m pip install communities
        python -m pip install brainspace

    - name: Lint
      run: |
        python -m pip install flake8
        flake8 . --count --select=E9,F63,F7,F82

    - name: Generate coverage report
      run: |
        python -m pip install pytest-cov
        pytest --sims --ci --cov-report xml:coverage.xml --cov=hypercoil

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml

    - name: Upload test results as artefact
      uses: actions/upload-artifact@v3
      with:
        name: SimulationResults
        path: hypercoil/examples/synthetic/results/
