name: CI
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10.4'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ‘2’
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade "jax[cpu]"
        python -m pip install --upgrade nox

    - name: Execute nox
      run: |
        nox

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml

    - name: Upload test results as artefact
      uses: actions/upload-artifact@v3
      with:
        name: SimulationResults
        path: hypercoil/examples/synthetic/results/
