name: doc
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10.4'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ‘2’
        submodules: recursive
        path: ./hypercoil

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        python -m pip install numpydoc
        python -m pip install pydata_sphinx_theme
        pushd hypercoil/
        python -m pip install .
        python -m pip install --upgrade --force-reinstall --no-deps https://github.com/deepmind/distrax/archive/4787902ae49ccfccb1c903e759d15bc61e6a20b4.tar.gz
        popd

    - name: Make HTML
      run: |
        pushd hypercoil/docs/
        python -m pip install -r requirements.txt
        make html
        popd

    - name: Upload HTML
      uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: hypercoil/docs/build/html/

    - name: Commit documentation changes
      run: |
        git clone https://github.com/hypercoil/hypercoil.github.io.git --branch pages-dev --single-branch pages-dev
        cp -r hypercoil/docs/build/html/* pages-dev/
        cd pages-dev/
        touch .nojekyll
        git config --local user.email "102877884+amalgam-amalgam@users.noreply.github.com"
        git config --local user.name "amalgam-amalgam"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.

    - name: Push changes
      run: |
        cd pages-dev
        git config --local user.email "102877884+amalgam-amalgam@users.noreply.github.com"
        git config --local user.name "amalgam-amalgam"
        git push https://${{ secrets.AMALGAM_AMALGAM }}@github.com/hypercoil/hypercoil.github.io.git
