name: doc
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.12'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ‘2’
        submodules: recursive
        path: ./hypercoil

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install dependencies
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        pushd hypercoil/
        python -m pip install .[doc,full]
        popd

    - name: Make HTML
      run: |
        pushd hypercoil/doc/
        python3 _scripts/build.py
        popd

    - name: Upload HTML
      uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: hypercoil/doc/_build/

    - name: Commit documentation changes
      run: |
        git clone https://github.com/hypercoil/hypercoil.github.io.git --branch pages-dev --single-branch pages-dev
        rm -rf pages-dev/*
        cp -r hypercoil/doc/_build/* pages-dev/
        cd pages-dev/
        touch .nojekyll
        git config --local user.email "102877884+amalgam-amalgam@users.noreply.github.com"
        git config --local user.name "amalgam-amalgam"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.

    - name: Push changes
      run: |
        cd pages-dev
        git config --local user.email "102877884+amalgam-amalgam@users.noreply.github.com"
        git config --local user.name "amalgam-amalgam"
        git push https://${{ secrets.AMALGAM_AMALGAM }}@github.com/hypercoil/hypercoil.github.io.git
